# Configuración del servidor
server.address=0.0.0.0
server.port=${PORT:5432}


# Configuración de la base de datos (PostgreSQL)
spring.datasource.url=postgresql://efarmaplus_postgres_user:hzq1oFZ0nasixeuxKKUhWRk2Z8OeN7qq@dpg-d4eh0p9r0fns73bnl6vg-a.oregon-postgres.render.com/efarmaplus_postgres
spring.datasource.username=efarmaplus_postgres_user
spring.datasource.password=hzq1oFZ0nasixeuxKKUhWRk2Z8OeN7qq
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# Configuración de Swagger/OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html


# Configuración de Jackson
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false